### ISSUE TITLE
Create backend route for testimonial form submission

### ISSUE THREAD

**Issue by cryptaliagy** [DudeRandom21/Stop-uOttawa-Surveillance#42]
A route needs to be created that will add the testimonial to the DB so that it can be extracted at a later time for a testimonials page.

The backend route will:

1) Authenticate that the user is a verified signer of the petition
2) Attach the first name + last initial (if last name was given), or simply 'Anonymous', the program/faculty name, the year code, and the comment to the DB, and the approval status of the testimonial
3) Send the comment to the Discord server for review by the team

Breaking this up into smaller ticket prerequisites

- [x] Modify DB drivers for testimonial saving/retrieving: #46 
- [ ] (OPTIONAL) Add route with some form of authentication to mark testimonials as approved: #47
- [ ] (OPTIONAL) Create a discord bot to auto-mark testimonials that get at least 51% thumbs-up in discord channel: #48

**Comment by cryptaliagy** [comment]
Closing as remaining tickets are optionals
