### ISSUE TITLE
Testimonials Page

### ISSUE THREAD

**Issue by cryptaliagy** [DudeRandom21/Stop-uOttawa-Surveillance#44]
A new page needs to be added to the Resources menu to display submitted student testimonials.

The page should query a backend route to receive a paginated list of approved testimonials. Ideally, it should also be implemented with an infinite-scroll type, but a simple table is also entirely sufficient for these purposes.

It should allow readers to filter:

- only/no anonymous [mutually exclusive]
- posts by students of specific year (mix & match)

If a table is made, it should allow readers to select how many posts they want to see per page from an option of 10, 15, 20 and 25 per page.

The backend route must be able to accept query parameters for the pointer to the last displayed testimonial so it can provide the next 'page'. It should also accept query parameters for the filters (anonymous/no_anonymous, 1/2/3/4/5/mst/phd).

There must also be a page to submit testimonials. This page will then post to an API route that will add the comment to the database and send it to the uPetition team for review

Ticket list:
- [x] Testimonial submission form frontend: #41 
- [x] Testimonial submission form backend: #42 
- [ ] Testimonial paginated retrieval: #43 
- [ ] Testimonial page frontend: #45

**Comment by cryptaliagy** [comment]
@DudeRandom21 @obenn @aMahanna I'm thinking for this epic we can do a rollout of the submission form when it is completed, and use it to collect testimonials while we build the page to let users view testimonials. What are y'all's thoughts on the matter?

**Comment by obenn** [comment]
Sounds good. I'd just to infinite scroll since I usually find it's easier to do than pagination and more consumable for the user but it doesn't really matter.

**Comment by cryptaliagy** [comment]
I have a tendency to consider the scalability of things that, at least at this moment don't really need scalability. I don't think we'll be getting thousands of testimonials so automating a lot of the approval process isn't really 'mission critical' and creating a proper endless scroll isn't terribly crucial either. For now I think the MVP will just be to display all approved with no pagination of the backend and if it becomes too much we can deal with it then
